---
version: '3'
services:
  app_postgres:
    image: docker.io/postgres:16
    env_file: .env
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_PASSWORD"

    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

    ports:
      - 15432:5432
volumes:
  pgdata: {}
