---
version: '3'
services:
  app_postgres:
    image: ghcr.io/fboulnois/pg_uuidv7
    env_file: .env
    environment:
      - "PGDATA=/var/lib/postgresql/data/pgdata"
      - "POSTGRES_PASSWORD"

    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

    ports:
      - 15432:5432

  rabbitmq:
    build:
      dockerfile: rabbitmq.Dockerfile
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  pgdata: {}
